tests:
  - name: Completness check for #### table
    sql: SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'schema_name' AND TABLE_NAME = 'tbl_name'
    expected: 1
  - name: test2
    sql: sql2
    expected: 0
  - name: test2
    sql: sql2
    expected: 0
